=begin
SUPERSEDE ReleasePlanner. Wrapper of Valentin's Implementation

No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end
class DefaultController < ApplicationController

  def add_skills_to_feature
    # Your code here
    i = 0
    result = Array.new
    beginh = 0;
    params[:features].each do |f|
      item = Hash.new
      item[:beginHour] = beginh
      item[:endHour] = beginh + f[:duration].to_d
      item[:feature] = f
      item[:resource] = params[:resources][i]
      result.push(item)
      i += 1
      i = 0 if i ==  params[:resources].length
      beginh = item[:endHour] + 1
    end
    render json: {:jobs => result}
   # render json: params
  end
end
